### ISSUE TITLE
Exploding Item Frames throws exception on regen

### ISSUE THREAD

**Issue by ryantheleach** [MicleBrick/ExplosionRegen#40]
When added as a regenerating entity, item frames cause exceptions to be spammed.

```
[23:02:04] [Server thread/WARN]: [ExplosionRegen] Task #163 for ExplosionRegen v4.0.0 generated an exception
java.lang.IllegalArgumentException: Cannot spawn hanging entity for org.bukkit.entity.ItemFrame at Location{world=CraftWorld{name=world-1.16.2},x=191.5,y=66.5,z=-74.96875,pitch=0.0,yaw=0.0} (no free face)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:383) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.createEntity(CraftWorld.java:1750) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawn(CraftWorld.java:1804) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawn(CraftWorld.java:1389) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at org.bukkit.craftbukkit.v1_16_R2.CraftWorld.spawnEntity(CraftWorld.java:652) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at net.starlegacy.explosionregen.Regeneration.regenerateEntity(Regeneration.java:90) ~[?:?]
        at net.starlegacy.explosionregen.Regeneration.regenerateEntities(Regeneration.java:79) ~[?:?]
        at net.starlegacy.explosionregen.Regeneration.pulse(Regeneration.java:21) ~[?:?]
        at net.starlegacy.explosionregen.ExplosionRegenPlugin.lambda$scheduleRegen$0(ExplosionRegenPlugin.java:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.2.jar:git-Spigot-379750e-eaf0bac]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by MicleBrick** [comment]
This should be fixed after the update
