### ISSUE TITLE
Cannot spawn an entity in 1.16.4

### ISSUE THREAD

**Issue by ThaMunsta** [MicleBrick/ExplosionRegen#43]
On Spigot 1.16.4 I occasionally run into an error that fills up the log files quickly.

[Server thread/WARN]: [ExplosionRegen] Task #14 for ExplosionRegen v4.0.0 generated an exception
java.lang.IllegalArgumentException: Cannot spawn an entity for org.bukkit.entity.Item
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.createEntity(CraftWorld.java:1779) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawn(CraftWorld.java:1804) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawn(CraftWorld.java:1389) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.spawnEntity(CraftWorld.java:652) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at net.starlegacy.explosionregen.Regeneration.regenerateEntity(Regeneration.java:90) ~[?:?]
	at net.starlegacy.explosionregen.Regeneration.regenerateEntities(Regeneration.java:79) ~[?:?]
	at net.starlegacy.explosionregen.Regeneration.pulse(Regeneration.java:21) ~[?:?]
	at net.starlegacy.explosionregen.ExplosionRegenPlugin.lambda$scheduleRegen$0(ExplosionRegenPlugin.java:44) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1059) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-f011ca2-3af81c7]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**Comment by ThaMunsta** [comment]
Oh sorry this may not be a bug. I was reading through #36 and have switched to paper. Hopefully that will either resolve things or give me more detail to provide ;)
Thanks, you guys rock!

**Comment by MicleBrick** [comment]
this is because i have to release a 1.16.4 version still. I made a 1.16.4 version a few days ago but didn't publish it yet.

**Comment by MicleBrick** [comment]
Releasing update now
