### ISSUE TITLE
Warnings in console - Unable to delete explosion_regen.dat_tmp

### ISSUE THREAD

**Issue by MrAusnadian** [MicleBrick/ExplosionRegen#6]
Getting the below error message using PaperMC 1.14.1 #42 (https://papermc.io/api/v1/paper/1.14.1/42/download)

`[18:28:28 WARN]: java.io.IOException: Unable to delete C:\Minecraft\.\creative\data\explosion_regen.dat_tmp
[18:28:28 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[18:28:28 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:137)
[18:28:28 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[18:28:28 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor25.execute(Unknown Source)
[18:28:28 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:28:28 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:28:28 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:28:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534)
[18:28:28 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[18:28:28 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.saveChunks(MinecraftServer.java:672)
[18:28:28 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1079)
[18:28:28 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904)
[18:28:28 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by MicleBrick** [comment]
Seems like a permissions error, it's not able to delete the file

**Comment by MicleBrick** [comment]
Might be something odd about the environment?

**Comment by MicleBrick** [comment]
It also might be something odd about Windows file paths, I haven't tested it other than on Linux. I'll investigate

**Comment by MicleBrick** [comment]
Very sorry but I am away from home until June 5th and will probably not be able to fix anything until then

**Comment by MicleBrick** [comment]
Sorry again, I went on another vacation after this and forgot about it. Getting home tomorrow. Could you clarify what the base folder in this testing case actually is?

**Comment by MrAusnadian** [comment]
Base folder is C:\Minecraft

**Comment by MicleBrick** [comment]
Should be in the latest version

**Comment by Mixikins** [comment]
Hiya! I just grabbed this one about an hour ago, and I am having this same issue on 2.1.0. I am running on a pure Spigot server. I don't have the issue when running the same server with Paper.

**Comment by MicleBrick** [comment]
Really? I don't see how this particular error is related to paper vs spigot at all... I'll set up a spigot test server I guess. Could you send the error log in case it's slightly different?

**Comment by Mixikins** [comment]
I was actually on my way to update this. It did happen on paper after a couple of minutes.
This is Windows Server 2012 R2, if it matters.


[15:49:15 INFO]: Mixikins[/192.168.1.1:60272] logged in with entity id 696 at ([MainWorld]46.16788310716904, 75.0, 178.76607372208989)
[15:53:00 WARN]: java.io.IOException: Unable to delete .\MainWorld\data\explosion_regen.dat_tmp
[15:53:00 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[15:53:00 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[15:53:00 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[15:53:00 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor74.execute(Unknown Source)
[15:53:00 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:53:00 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:53:00 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:53:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[15:53:00 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:53:00 WARN]: java.io.IOException: Unable to delete .\MainWorld_nether\data\explosion_regen.dat_tmp
[15:53:00 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[15:53:00 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[15:53:00 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[15:53:00 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor74.execute(Unknown Source)
[15:53:00 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:53:00 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:53:00 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:53:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[15:53:00 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:53:00 WARN]: java.io.IOException: Unable to delete .\MainWorld_the_end\data\explosion_regen.dat_tmp
[15:53:00 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[15:53:00 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[15:53:00 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[15:53:00 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor74.execute(Unknown Source)
[15:53:00 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:53:00 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:53:00 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:53:00 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[15:53:00 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[15:53:00 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Mixikins** [comment]
Here it is on Spigot.
`[16:17:19] [Server thread/WARN]: java.io.IOException: Unable to delete .\MainWorld\data\explosion_regen.dat_tmp
[16:17:19] [Server thread/WARN]:        at com.google.common.io.Files.move(Files.java:485)
[16:17:19] [Server thread/WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[16:17:19] [Server thread/WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[16:17:19] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:17:19] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[16:17:19] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[16:17:19] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[16:17:19] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[16:17:19] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:17:19] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520)
[16:17:19] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505)
[16:17:19] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:749)
[16:17:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftWorld.save(CraftWorld.java:1084)
[16:17:19] [Server thread/WARN]:        at com.wimbli.WorldBorder.WorldFillTask.reportProgress(WorldFillTask.java:526)
[16:17:19] [Server thread/WARN]:        at com.wimbli.WorldBorder.WorldFillTask.run(WorldFillTask.java:282)
[16:17:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[16:17:19] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[16:17:19] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1011)
[16:17:19] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[16:17:19] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:959)
[16:17:19] [Server thread/WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804)
[16:17:19] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)`

**Comment by MrAusnadian** [comment]
Still the same issue on paper-120.jar:

`[16:48:21 WARN]: java.io.IOException: Unable to delete .\world\data\explosion_regen.dat_tmp
[16:48:21 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[16:48:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[16:48:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:48:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:48:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:48:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:48:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:48:21 WARN]: java.io.IOException: Unable to delete .\world_nether\data\explosion_regen.dat_tmp
[16:48:21 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[16:48:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[16:48:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:48:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:48:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:48:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:48:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:48:21 WARN]: java.io.IOException: Unable to delete .\world_the_end\data\explosion_regen.dat_tmp
[16:48:21 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[16:48:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[16:48:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:48:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:48:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:48:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:48:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:48:21 WARN]: java.io.IOException: Unable to delete .\brave_new_world\data\explosion_regen.dat_tmp
[16:48:21 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[16:48:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[16:48:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:48:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:48:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:48:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:48:21 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:48:21 WARN]: java.io.IOException: Unable to delete .\creative\data\explosion_regen.dat_tmp
[16:48:21 WARN]:        at com.google.common.io.Files.move(Files.java:485)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:136)
[16:48:21 WARN]:        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48)
[16:48:21 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor101.execute(Unknown Source)
[16:48:21 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[16:48:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[16:48:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:48:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:758)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1090)
[16:48:21 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908)
[16:48:21 WARN]:        at java.lang.Thread.run(Thread.java:748)`

**Comment by MicleBrick** [comment]
I don't use Windows on either my computer or my server, so I can't test this easily, but I will try something when I get home and you can test it. If you have Discord, join this, it'll make it easier to communicate: https://discord.gg/hzg4Eh

**Comment by MicleBrick** [comment]
Fixed in 2.2.0
